[versions]
agp = "8.13.1"
kotlin = "2.2.21"
kotlinxCoroutinesCore = "1.10.2"
android-minSdk = "26"
android-compileSdk = "36"
vanniktechMavenPublish = "0.35.0"
apache-commons = "3.19.0"
gson = "2.13.2"
json = "20250517"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
apache-commons = { module = "org.apache.commons:commons-lang3",  version.ref = "apache-commons"}
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
json = { module = "org.json:json", version.ref = "json" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }